// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbbxgshioznuwpymiaer.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiYnhnc2hpb3pudXdweW1pYWVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzU4ODMsImV4cCI6MjA3MjE1MTg4M30.ROUh9rHA8TsFLrtKVCnlPjueY3JanxAz3Uag2i3SSEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});